//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLIMSEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HLIMSystemEntities : DbContext
    {
        public HLIMSystemEntities(string connection): base(connection)
        {
            
        }
        public HLIMSystemEntities()
            : base("name=HLIMSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBank> tblBanks { get; set; }
        public virtual DbSet<tblInsurence> tblInsurences { get; set; }
        public virtual DbSet<tblBorrower> tblBorrowers { get; set; }
        public virtual DbSet<tblProperty> tblProperties { get; set; }
        public virtual DbSet<tblLoan> tblLoans { get; set; }
    }
}
