//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLIMSEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        public int Id { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> OriginalTenure { get; set; }
        public Nullable<decimal> ReminingAmount { get; set; }
        public Nullable<decimal> ReminingTenure { get; set; }
        public Nullable<int> BorrowerId { get; set; }
    
        public virtual tblBorrower tblBorrower { get; set; }
    }
}
